name: rentcarapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  get: 4.6.5
  get_storage: ^2.0.3
  flutter: 
    sdk: flutter
  responsive_framework: ^0.2.0
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  image_path: "assets/img/1024.png"
  android: true
  ios: true

flutter: 
  uses-material-design: true
  assets:
    - assets/font/
    - assets/img/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-Medium.ttf
          weight: 300

