// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxkkVIAAecmkmvNR1gZz5sbDq0Grh0OZ0',
    appId: '1:397511950748:web:01559f82d5437d7a554859',
    messagingSenderId: '397511950748',
    projectId: 'rentcarapp-dd749',
    authDomain: 'rentcarapp-dd749.firebaseapp.com',
    storageBucket: 'rentcarapp-dd749.appspot.com',
    measurementId: 'G-MD6VQRJH0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGIAJXpU4WmJATlMxRAv4K7-Ym8WNqKBI',
    appId: '1:397511950748:android:af689962c4ebd850554859',
    messagingSenderId: '397511950748',
    projectId: 'rentcarapp-dd749',
    storageBucket: 'rentcarapp-dd749.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOY-PfNifBPze3mB4aZLDPLa-M5mD4RuQ',
    appId: '1:397511950748:ios:64b7d9125c315169554859',
    messagingSenderId: '397511950748',
    projectId: 'rentcarapp-dd749',
    storageBucket: 'rentcarapp-dd749.appspot.com',
    iosClientId: '397511950748-iev65tkm7bncjicn3jbhnbimk06598ra.apps.googleusercontent.com',
    iosBundleId: 'com.rentcarapp.rentcarapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOY-PfNifBPze3mB4aZLDPLa-M5mD4RuQ',
    appId: '1:397511950748:ios:64b7d9125c315169554859',
    messagingSenderId: '397511950748',
    projectId: 'rentcarapp-dd749',
    storageBucket: 'rentcarapp-dd749.appspot.com',
    iosClientId: '397511950748-iev65tkm7bncjicn3jbhnbimk06598ra.apps.googleusercontent.com',
    iosBundleId: 'com.rentcarapp.rentcarapp',
  );
}
